### ISSUE TITLE
Description for DockerHub page

### ISSUE THREAD

**Issue by mcandre** [jeff-svds/kafka-connect-opentsdb#1]
Please add a description of the [DockerHub](https://hub.docker.com/r/jeffsvds/kafka-connect-opentsdb/) entry for kafka-connect-opentsdb, so that people know what this image is for.

Please also link back from the DockerHub page to this GitHub repo to make it easier for people to track down the source code.

**Comment by jeff-svds** [comment]
Done. Thanks for the feedback @mcandre
